### ISSUE TITLE
1 bug 1 suggestion

### ISSUE THREAD

**Issue by Stanzilla** [ivanwonder/hyper-open-tab-in-system-context-menu#1]
Hey there, love your plugin, noticed two things though:

1) It does not work when using a WSL shell, such as zsh in my case. It does not carry over the directory in that case, the tab opens just fine though.

2) Can you make Hype come to the front and get focus when the tab gets opened? That would nice!

**Comment by Enteleform** [comment]
### +1
for focusing the window on new tab creation

**Comment by ivanwonder** [comment]
@Stanzilla about the first bug. I change my shell to Bash on Windows in `.hyper.js`, and work fine for me, open the correct directory. I cannot reproduce your problem. Maybe the problem is happen on hyper app. you can try that after uninstall my plugin. the plugin just pass the arguments 'cwd' to hyper app.

the second suggestion, i will fix it soon.

**Comment by ivanwonder** [comment]
@Stanzilla @Enteleform  I have published the second suggestion improvement.

**Comment by Stanzilla** [comment]
Oh that's weird indeed. It works now with zsh! Thanks! Focus is also working great! Might be worth noting that a restart of Hyper is needed for it to work, though.
